Update deps, add missing `format`
With the latest version of nixpkgs, the build started failing:

```
$ nix build .
...
error: with-alacritty-1.0 does not configure a `format`. To build with setuptools as before, set `pyproject = true` and `build-system = [ setuptools ]`.`
```

This fixes that.