Remove deprecated `pytestFlagsArray`
I had to switch to the `nixpkgs-unstable` channel (which we should have
been using anyways, as we don't depend on having any nixos specific
packages built) and run `nix flake update` to pull in
<https://github.com/nixos/nixpkgs/commit/82da9cf45c21f9b93b48d8ef40ff6005dfc5a53b>
to reproduce the issue.

Before:

```console
$ nix build
...
       error: buildPythonPackage: Deprecated flag pytestFlagsArray found at /nix/store/hq0pksqsjg00yi5d8vz7np3hcz9p7mps-source/nix/derivation.nix:18
         Use pytestFlags or (enabled|disabled)(TestPaths|Tests|TestMarks) instead.
```

After:

```console
$ nix build
$
```